In [2]:
import pickle as pkl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


import arviz as az
import pymc3 as pm

In [19]:
# load data
with open('../data/shuangseqiu.pkl', 'rb') as f:
    data = pkl.load(f)
    
    
df = pd.DataFrame(data)[['date', 'red_balls', 'blue_ball']]
for i in range(6):
    df[f'red_ball_{i+1}'] = df['red_balls'].apply(lambda x: x[i])

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date', ascending=True).reset_index(drop=True)
df.tail()

,date,red_balls,blue_ball,red_ball_1,red_ball_2,red_ball_3,red_ball_4,red_ball_5,red_ball_6
2769,2021-11-04,"[19, 20, 23, 27, 28, 31]",1,19,20,23,27,28,31
2770,2021-11-07,"[7, 15, 16, 20, 27, 29]",7,7,15,16,20,27,29
2771,2021-11-09,"[5, 17, 20, 21, 23, 33]",4,5,17,20,21,23,33
2772,2021-11-11,"[4, 15, 21, 27, 28, 29]",10,4,15,21,27,28,29
2773,2021-11-14,"[8, 9, 15, 24, 26, 30]",6,8,9,15,24,26,30

In [27]:
def as_binary_repr(x, total):
    out = np.zeros(total, dtype=int)
    index = np.asarray(x) - 1
    out[index] = 1
    return out

df['red_ball_binary'] = df['red_balls'].apply(lambda x: as_binary_repr(x, 33))
df['blue_ball_binary'] = df['blue_ball'].apply(lambda x: as_binary_repr(x, 16))
df.head()

,date,red_balls,blue_ball,red_ball_1,red_ball_2,red_ball_3,red_ball_4,red_ball_5,red_ball_6,red_ball_binary,blue_ball_binary
0,2003-02-23,"[10, 11, 12, 13, 26, 28]",11,10,11,12,13,26,28,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]"
1,2003-02-27,"[4, 9, 19, 20, 21, 26]",12,4,9,19,20,21,26,"[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]"
2,2003-03-02,"[1, 7, 10, 23, 28, 32]",16,1,7,10,23,28,32,"[1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
3,2003-03-06,"[4, 6, 7, 10, 13, 25]",3,4,6,7,10,13,25,"[0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,2003-03-09,"[4, 6, 15, 17, 30, 31]",16,4,6,15,17,30,31,"[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"

In [54]:
observed_red = np.vstack(df['red_ball_binary'].head(5).values)
observed_blue = np.vstack(df['blue_ball_binary'].head(5).values)

# Approach 1
红球范围1-33，蓝球范围1-16。将红球和篮球分别用[Dirichilet](https://docs.pymc.io/en/v3/api/distributions/multivariate.html#pymc3.distributions.multivariate.Dirichlet)分布表示

In [59]:
def _uniform_init(n):
    return np.ones(n) / n

with pm.Model():
    red_prob = pm.Dirichlet(name='red_prob', a=[0.5] * 33)
    blue_prob = pm.Dirichlet(name='blue_prob', a=[0.5] * 16)
#     red_prob = pm.Normal(name='red_prob', mu=0.5, sigma=0.1, shape=33)
#     blue_prob = pm.Normal(name='blue_prob', mu=0.5, sigma=0.1, shape=16)
    
    red = pm.DirichletMultinomial('red_ball', n=6, a=red_prob, shape=33, observed=observed_red)
    blue = pm.DirichletMultinomial('blue_ball', n=1, a=blue_prob, shape=16, observed=observed_blue)
    idata = pm.sample(2000, tune=1500, return_inferencedata=True)

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...

SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'red_prob': array([ 1.27625707,  0.63737476, -0.06737107, -0.19983886,  0.14061779,
       -0.31818266,  1.3170643 ,  1.13320004,  1.22697506, -0.03166434,
       -0.08640564,  1.27855327,  0.04991121, -0.24891553,  0.24643823,
        0.09603451, -0.15086491,  0.86810405,  0.85080596,  0.42832146,
        0.63461884, -0.44579602,  0.58602761,  0.4728631 ,  0.86945063,
        1.00973617, -0.39872832,  0.69649681, -0.11899527,  0.0435443 ,
        0.87011438,  1.15042334,  0.6838015 ]), 'blue_prob': array([ 1.12929188,  0.24758612, -0.23163979,  0.68402935,  1.05241439,
       -0.05815099,  1.24220833,  1.17447662,  0.39098879, -0.23230258,
        0.3222111 ,  0.28133811,  0.26431591,  1.36139468,  1.28134653,
        1.30261457])}

Initial evaluation results:
red_prob    -458.76
blue_prob   -244.42
red_ball       -inf
blue_ball      -inf
Name: Log-probability of test_point, dtype: float64